from pandasdb.communication.errors.base import PandasDBException


class PandasDBDataValidationError(PandasDBException):
    pass
