CHANGELOG.rst,sha256=0ZyHMPhd88zq4MNjSRvMt6AyJWhfDCMMPVleTH05QvA,8709
django_auth_adfs/__init__.py,sha256=b2IY4CVT2nx2Z4xfQJ0-bPvnMP5PfSVae2Cftt9xuNU,136
django_auth_adfs/backend.py,sha256=K-yXAFgIqAWtYX8Sb11hdvOD19lsjzXJJk9RAPjzfsI,12906
django_auth_adfs/config.py,sha256=QmkJvGb5ZiIS6ABz7qKc-d9hfU2YAcTqcpYM_QVhiaY,15193
django_auth_adfs/drf-urls.py,sha256=bBnN1WrgbHoiAs5hTGe-ovmVwwJ4D2xXpYtZVfE8l5U,221
django_auth_adfs/drf_urls.py,sha256=6mgMfGyrU9ftQimVHyQcck_nWT2WRuGov-AEe4OiFOc,352
django_auth_adfs/exceptions.py,sha256=yxwKHtDSMnskgBdIQoCWerYVr8sGtIn26GWVVdhA2YU,110
django_auth_adfs/middleware.py,sha256=st8Hx5pHWNcYUNWrCQht3QJqjw6RLQhWyxneTWal0Nw,2249
django_auth_adfs/rest_framework.py,sha256=spWIXpb8UtVDvZ0_W_sJB-5u0hwvLNUCqbAhHf9N0W4,1656
django_auth_adfs/signals.py,sha256=HGD79-dZNEwqVuINoqe6jB_8K1RfuK5Q288RGamTtEU,137
django_auth_adfs/templates/django_auth_adfs/login_failed.html,sha256=1NQ5aCjo7iTLSxy2IXJZbzBp5MaxpfsfQwQ_PDFvgr4,652
django_auth_adfs/urls.py,sha256=jVZBG6BLAiFU0NG2y37Io3OQTQ2mQMtTGK5xEE6dP5Q,538
django_auth_adfs/views.py,sha256=gkT4e9hoGIUiL9364LjSL4SSyZAU3RKvP6S1cZLLncA,3932
django_auth_adfs-1.8.0.dist-info/LICENSE,sha256=n3ImkhGUnnJEu1sT51QKc_N22WdixSRcrfg9gj6nr3c,1296
django_auth_adfs-1.8.0.dist-info/WHEEL,sha256=SrtnPGVTMeYWttls9xnWA01eUhCZ3ufFdJUYb1J3r-U,83
django_auth_adfs-1.8.0.dist-info/METADATA,sha256=z8WmMC6HuhUnUkkqef0Iw2Y4Tn6TOXUnqxnwpK-cFRI,5822
django_auth_adfs-1.8.0.dist-info/RECORD,,
